spring:
  datasource:
    - name: db1
      url: jdbc:mysql://localhost:3306/my_db?useSSL=false&serverTimezone=UTC
      username: yurko
      password: yurko
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
    - name: db2
      url: jdbc:postgresql://localhost:5432/myDb
      username: postgres
      password: yurko
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect