#spring:
#  datasource:
#    - name: db1
#      driver-class-name=org.postgresql.Driver
#      url: jdbc:mysql://localhost:3306/data_base_1?useSSL=false&serverTimezone=UTC
#      username: yurko
#      password: yurko
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQL8Dialect
#    - name: db2
#      driver-class-name=com.mysql.cj.jdbc.Driver.
#      url: jdbc:postgresql://localhost:5432/data_base_2
#      username: postgres
#      password: yurko
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect

#springdoc-swagger-ui: path=/swagger-ui.html
#springdoc:
#  api-docs: path=/api-docs